[package]
name = "wasm-test"
version = "0.0.0"
edition = "2018"

[dependencies]
surf-cookie-middleware = { path = ".." }
surf = { version = "2.3.1", default-features = false, features = ["wasm-client"] }
wasm-bindgen-test = "0.3.26"
async-std = "1.9.0"
serde_json = "1.0.66"

